### PR TITLE
Try to make the UI prettier

### PR DESCRIPTION
**Pull request by honza**
This uses [Twitter Bootstrap](http://twitter.github.com/bootstrap/). The grid and modals are redesigned. 

Let me know if you have any suggestions.

### CODE REVIEW

**Comment by wolfe** [comment]
It's much better.  EXCEPT,  I'd really like to conserve whitespace better.
 I know nobody else wants lots of data packed in, but I do.

How hard is it to make every 5th vertical and horizontal line dark?  I'd
prefer that to what we do now with alternating colors on the rows.

David

On Sat, Jan 28, 2012 at 8:22 PM, Honza Pokorny <
reply@reply.github.com

> wrote:
> 
> This uses [Twitter Bootstrap](http://twitter.github.com/bootstrap/). The
> grid and modals are redesigned.
> 
> Let me know if you have any suggestions.
> 
> You can merge this Pull Request by running:
> 
>  git pull https://github.com/SheepDogInc/ssheepdog bootstrap
> 
> Or you can view, comment on it, or merge it online at:
> 
>  https://github.com/SheepDogInc/ssheepdog/pull/5
> 
> -- Commit Summary --
> - Initial pass
> 
> -- File Changes --
> 
> M src/ssheepdog/static/css/base.css (42)
> A src/ssheepdog/static/css/bootstrap-base.css (5)
> A src/ssheepdog/static/css/bootstrap.min.css (356)
> A src/ssheepdog/static/js/jquery-client.js (32)
> A src/ssheepdog/templates/bootstrap_base.html (34)
> M src/ssheepdog/templates/view_grid.html (42)
> 
> -- Patch Links --
> 
>  https://github.com/SheepDogInc/ssheepdog/pull/5.patch
>  https://github.com/SheepDogInc/ssheepdog/pull/5.diff
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/SheepDogInc/ssheepdog/pull/5

## 

David Wolfe, PhD
R&D Team Lead
SheepDogInc.ca | Information's best friend.

1-888-807-5765
902-442-8228 direct
902-446-7043 fax

**Comment by thurloat** [comment]
I'd love to leave some feedback, however I can't create logins to preview the table locally

**Comment by wolfe** [comment]
The dev branch has a fix to that.

David

On Sat, Jan 28, 2012 at 11:21 PM, Adam Thurlow <
reply@reply.github.com

> wrote:
> 
> I'd love to leave some feedback, however I can't create logins to preview
> the table locally
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/SheepDogInc/ssheepdog/pull/5#issuecomment-3706289

## 

David Wolfe, PhD
R&D Team Lead
SheepDogInc.ca | Information's best friend.

1-888-807-5765
902-442-8228 direct
902-446-7043 fax

**Comment by honza** [comment]
Highlighting every 5th row shouldn't be hard. It's just an `tr:nth-child` in css.

**Comment by wolfe** [comment]
Sorry -- What I hadn't seen much of but might be cleaner is having a
thicker division between the 5th and 6th rows, between the 10th and 11
rows, etc.

David

On Sun, Jan 29, 2012 at 12:00 PM, Honza Pokorny <
reply@reply.github.com

> wrote:
> 
> Highlighting every 5th row shouldn't be hard. It's just an `tr:nth-child`
> in css.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/SheepDogInc/ssheepdog/pull/5#issuecomment-3709102

## 

David Wolfe, PhD
R&D Team Lead
SheepDogInc.ca | Information's best friend.

1-888-807-5765
902-442-8228 direct
902-446-7043 fax

**Comment by honza** [comment]
I just force-rebased this branch on top of `dev`. It should include David's fix for the `Login`-related issues.

**Pull request merged**
